# Generated by Django 3.0.5 on 2020-06-10 11:05

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'unknow'), (1, 'female'), (2, 'male')], default=0, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('user_name', models.CharField(max_length=10)),
                ('avatar', models.CharField(blank=True, max_length=128, null=True)),
                ('bg', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_ time', null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
