# Generated by Django 3.0.5 on 2020-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.IntegerField()),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('user_name', models.CharField(max_length=10)),
                ('avatar', models.CharField(blank=True, max_length=128, null=True)),
                ('bg', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_ time', null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
