# Generated by Django 3.0.5 on 2020-06-10 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200610_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, db_column='create_ time', default=datetime.datetime(2020, 6, 10, 11, 38, 39, 100291, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 11, 38, 39, 100291, tzinfo=utc), null=True),
        ),
    ]
